env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules:
  semi:
    - error
    - always
  indent:
    - error
    - 2
